matrix:
- name: markdown
  sources:
  - README.md
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .dictionary.txt
    output: build/dictionary/dictionary.dic
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
      - pymdownx.highlight:
      - pymdownx.striphtml:
      - pymdownx.magiclink:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:

- name: python
  sources:
  - setup.py
  - "{coloraide_extras,tests,tools}/**/*.py"
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .dictionary.txt
    output: build/dictionary/dictionary.dic
  pipeline:
  - pyspelling.filters.python:
      group_comments: True
  - pyspelling.flow_control.wildcard:
      allow:
      - py-comment
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore lint (noqa) and coverage (pragma) as well as shebang (#!)
      - open: '^(?: *(?:noqa\b|pragma: no cover|type: .*?)|!)'
        close: '$'
      # Ignore Python encoding string -*- encoding stuff -*-
      - open: '^ *-\*-'
        close: '-\*-$'
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`]'
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
  - pyspelling.filters.url:
