site_name: ColorAide Extras Documentation
site_url: https://facelessuser.github.io/coloraide-extras
repo_url: https://github.com/facelessuser/coloraide-extras
edit_uri: ""
site_description: Additional color spaces for ColorAide
copyright: |
  Copyright &copy; 2014 - 2025 <a href="https://github.com/facelessuser" target="_blank" rel="noopener">Isaac Muse</a>

docs_dir: docs/src/markdown
theme:
  custom_dir: docs/theme
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - search.share
    - search.highlight
    - search.suggest
  pymdownx:
    sponsor: "https://github.com/sponsors/facelessuser"

nav:
  - ColorAide Extras:
      - Introduction: index.md
      - Color Spaces:
        - colors/index.md
        - CIE 1964 UVW: colors/uvw.md
      - Color Interpolation:
        - interpolate/index.md
        - Spectral: interpolate/spectral.md
      - Color Contrast:
        - contrast/index.md
        - Weber Contrast: contrast/weber.md
        - Michelson Contrast: contrast/michelson.md
  - Playground: playground.md
  - About:
      - Contributing &amp; Support: about/contributing.md
      - Changelog: about/changelog.md
      - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: playground
          class: playground
          format: !!python/object/apply:docs.src.py.notebook.color_command_formatter
            kwds:
              init: |
                import coloraide
                import coloraide_extras
                from coloraide import *
                from coloraide_extras.everything import ColorAll as Color
          validator: !!python/name:docs.src.py.notebook.color_command_validator
        - name: py
          class: 'highlight'
          format: !!python/object/apply:docs.src.py.notebook.color_command_formatter
            kwds:
              init: |
                import coloraide
                import coloraide_extras
                from coloraide import *
                from coloraide_extras.everything import ColorAll as Color
          validator: !!python/name:docs.src.py.notebook.color_command_validator
        - name: python
          class: 'highlight'
          format: !!python/object/apply:docs.src.py.notebook.color_command_formatter
            kwds:
              init: |
                import coloraide
                import coloraide_extras
                from coloraide import *
                from coloraide_extras.everything import ColorAll as Color
          validator: !!python/name:docs.src.py.notebook.color_command_validator
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: color
          class: color
          format: !!python/object/apply:docs.src.py.notebook.color_formatter
            kwds:
              init: |
                import coloraide
                import coloraide_extras
                from coloraide import *
                from coloraide_extras.everything import ColorAll as Color
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: coloraide-extras
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/.snippets
      - LICENSE.md
      auto_append:
      - refs.md
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.saneheaders:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
      types:
      - name: details-new
        class: new
      - name: details-settings
        class: settings
      - name: details-note
        class: note
      - name: details-abstract
        class: abstract
      - name: details-info
        class: info
      - name: details-tip
        class: tip
      - name: details-success
        class: success
      - name: details-question
        class: question
      - name: details-warning
        class: warning
      - name: details-failure
        class: failure
      - name: details-danger
        class: danger
      - name: details-bug
        class: bug
      - name: details-example
        class: example
      - name: details-quote
        class: quote
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True
  - pymdownx.fancylists:
      inject_style: True
  - pymdownx.blocks.caption:

extra_css:
  - assets/coloraide-extras/extra-71ac3701da.css
  - https://cdn.jsdelivr.net/npm/ace-builds@1.43.0/css/ace.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/ace-builds@1.43.0/src-min-noconflict/ace.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.7.0/dist/mermaid.min.js
  - playground-config-0ba7e885.js
  - https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js
  - assets/coloraide-extras/extra-notebook-DQMNiD5r.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocs_pymdownx_material_extras
  - minify:
      minify_html: true
